version: '3'
services:

  #PHP Service
  app:
    depends_on:
      - db
      - redis
    build: Dockerfile
    container_name: php
    entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - .:/var/www
    networks:
      - app-network2

  #Nginx Service
  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    environment:
      - APPLICATION_NAME=app
      - APPLICATION_PORT=9000
    depends_on:
      - app
    networks:
      - app-network2

  db:
    #image: mysql:5.7
    build: .docker/mysql
    command: --innodb-use-native-aio=0
    container_name: db
    tty: true
    ports:
      - "3301:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-network2

  #Redis Service
  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379
    networks:
      - app-network2

networks:
  app-network2:
    driver: bridge
