version: '3.7'
services:

  #PHP Service
  app:
    depends_on:
      - db
    build: .
    container_name: php
    volumes:
     - .:/var/www
    networks:
      - app-network

  #Nginx Service
  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - app-network

  db:
    #image: mysql:5.7
    build: .docker/mysql
    command: --innodb-use-native-aio=0
    container_name: db
    tty: true
    ports:
      - "3301:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-network

  #Redis Service
  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
